### ISSUE TITLE
Torrent File Info文件大小显示不正常

### ISSUE THREAD

**Issue by MyACGN** [laoqiuqiu/DOpus-Script#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Torrent File Info文件大小显示不正常

**Comment by laoqiuqiu** [comment]
怎么个不正常？

**Comment by MyACGN** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "laoqiuqiu/DOpus-Script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月21日(星期天) 上午10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [laoqiuqiu/DOpus-Script] Torrent File Info文件大小显示不正常 (Issue #1)





 
怎么个不正常？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
